secret_key = "12345678901234567890123456789012345678901235"
admins = ["jackson@example.com"]

[oauth.github]
client_id = "<client_id>"
client_secret = "<client_secret>"

[oauth.google]
client_id = "<client_id>"
client_secret = "<client_secret>"
